force-app/main/default/objects/AI_obj_RoleAndContent__c/AI_obj_RoleAndContent__c.object-meta.xml
<CustomObject>
    <label>AI Role And Content</label>
    <nameField>
        <label>AI RoleAndContent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Roles And Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_obj_RoleAndContent__c/fields/conversation__c.field-meta.xml
<CustomField>
    <fullName>conversation__c</fullName>
    <label>AI Conversation</label>
    <referenceTo>AI_obj_Conversation__c</referenceTo>
    <relationshipLabel>AI Roles And Contents</relationshipLabel>
    <relationshipName>AI_Roles_And_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassDeleteExtension.cls
// Extension to delete all of the selected objects
public with sharing class MassDeleteExtension {

    ApexPages.StandardSetController setCon;
    public String error { get; set; }
    public PageReference originalUrl { get; set; }

    public MassDeleteExtension(ApexPages.StandardSetController controller) {
        setCon = controller;
    }

    public String getMySelectedSize() {
        return setCon.getSelected().size() + '';
    }
    
    public PageReference deleteRecords(){
        originalUrl = setCon.cancel();
        System.debug(setCon.getSelected());
        System.debug([SELECT Id, Name, conversation__c FROM AI_obj_RoleAndContent__c WHERE Id IN :setCon.getSelected()]);

        delete [SELECT Id, Name, conversation__c FROM AI_obj_RoleAndContent__c WHERE Id IN :setCon.getSelected()];
        return originalUrl;
    }

}